String getRandomHealthTip(String timeOfDay) {
  Map<String, List<String>> healthTips = {
    'morning': [
      'Start your day with a mindful breathing exercise.',
      'Include a variety of colors in your breakfast for diverse nutrients.',
      'Try a new morning workout routine for added variety.',
      'Express gratitude for three things in your morning routine.',
      'Explore different breakfast recipes to keep things interesting.',
      'Take a moment to set a positive intention for the day ahead.',
      'Read a short motivational article to kickstart your day.',
      'Incorporate leafy greens into your morning smoothie.',
      'Practice a quick morning meditation for mental clarity.',
      'Enjoy a warm cup of herbal tea as part of your morning ritual.',
      'Create a morning playlist with uplifting and energizing songs.',
      'Write down your top three priorities for the day.',
      'Include a source of omega-3 fatty acids in your breakfast.',
      'Set aside time for morning journaling to reflect on your thoughts.',
      'Incorporate a variety of textures into your breakfast for satisfaction.',
      'Practice deep breathing exercises for relaxation.',
      'Take a moment to appreciate the natural light in the morning.',
      'Include a source of protein in your breakfast for sustained energy.',
      'Try a morning stretching routine to wake up your muscles.',
      'Plan a morning walk to enjoy the beauty of nature.',
      'Opt for a mindful breakfast, savoring each bite.',
      'Include nuts or seeds in your breakfast for added nutrition.',
      'Set a positive affirmation for the day ahead.',
      'Take a moment of silence for reflection before starting your day.',
      'Plan a morning routine that aligns with your goals.',
      'Practice gratitude by acknowledging positive aspects of your life.',
      'Incorporate a source of vitamin C into your morning routine.',
      'Create a morning ritual around your favorite beverage.',
      'Write down one thing you\'re looking forward to today.',
      'Include a source of fiber in your morning meal for digestion.',
      'Set a goal for personal or professional growth in the morning.',
      'Take a moment to express kindness to yourself and others.',
      'Plan a morning break to enjoy a brief mindfulness meditation.',
      'Incorporate a source of calcium into your morning routine.',
      'Enjoy a morning cup of green tea for a gentle caffeine boost.',
      'Snack on a piece of fruit for a natural energy boost.',
      'Take a moment to appreciate the stillness of the morning.',
      'Plan a morning break to engage in a hobby or creative activity.',
      'Incorporate a source of vitamin D into your morning routine.',
      'Practice a morning visualization exercise for success.',
      'Include a variety of colors in your morning meal.',
      'Snack on a handful of berries for antioxidant benefits.',
      'Take a moment to express gratitude for the morning tranquility.',
      'Plan a morning break to listen to an inspiring podcast.',
      'Incorporate a source of iron into your morning routine.',
      'Enjoy a morning cup of chamomile tea for a calming break.',
      'Snack on a piece of dark chocolate for a mood boost.',
      'Take a moment to appreciate the achievements of the morning.',
      'Plan a morning break to engage in a positive conversation.',
      'Incorporate a source of magnesium into your morning routine.',
      'Use a morning break to connect with nature, even if briefly.',
      'Opt for a light and refreshing morning salad.',
      'Snack on a piece of celery for a hydrating option.',
      'Take a moment to appreciate the natural sounds of the morning.',
      'Plan a morning break to enjoy a piece of art or nature.',
      'Incorporate a source of vitamin A into your morning routine.',
      'Practice a morning gratitude exercise, acknowledging positive aspects.',
      'Include a source of potassium in your morning routine.',
      'Use a morning break to engage in a quick positive visualization.',
      'Snack on a handful of mixed nuts for a balanced morning option.',
      'Take a moment to express gratitude for the morning pause.',
      'Plan a morning break to enjoy a brief mindfulness breathing exercise.',
      'Incorporate a source of vitamin K into your morning routine.',
      'Enjoy a morning cup of ginger tea for a warming break.',
      'Snack on a piece of cucumber for a hydrating option.',
      'Take a moment to appreciate the natural sounds of the morning.',
      'Opt for a light and refreshing morning smoothie.',
      'Practice a morning desk exercise to enhance circulation.',
      'Include a source of manganese in your morning routine.',
      'Use a morning break to engage in a positive self-talk exercise.',
      'Snack on a handful of blueberries for a refreshing option.',
      'Take a moment to express kindness to yourself and others.',
      'Plan a morning break to enjoy a brief mindfulness visualization.',
      'Incorporate a source of phosphorus into your morning routine.',
      'Enjoy a morning cup of rooibos tea for a caffeine-free break.',
      'Snack on a piece of pineapple for a tropical morning option.',
      'Take a moment to appreciate the beauty of the morning sky.',
      'Opt for a morning meal with a variety of spices for flavor.',
      'Practice a morning desk stretch to alleviate tension and improve posture.',
      'Include a source of selenium in your morning routine.',
      'Use a morning break to engage in a positive affirmation practice.',
      'Snack on a handful of strawberries for a refreshing morning option.',
      'Take a moment to express gratitude for the morning tranquility.',
      'Plan a morning break to enjoy a brief mindfulness gratitude exercise.',
      'Incorporate a source of potassium into your morning routine.',
      'Enjoy a morning cup of chamomile tea for a calming break.',
      'Snack on a piece of watermelon for a hydrating morning option.',
      'Take a moment to appreciate the warmth of the morning.',
      'Opt for a morning meal with a mix of textures and temperatures for enjoyment.',
      'Practice a morning mindfulness exercise, focusing on your breath and surroundings.',
      'Include a source of vitamin E in your morning routine.',
      'Use a morning break to engage in a positive visualization and affirmations.',
      'Snack on a handful of almonds for a satisfying and nutritious morning option.',
      'Take a moment to express kindness to yourself and others.',
    ],
    'midday': [
      'Stay hydrated by drinking water throughout the midday.',
      'Take short breaks to stand up and stretch your muscles.',
      'Enjoy a balanced lunch with a mix of proteins and vegetables.',
      'Snack on nuts or fruits for a healthy energy boost.',
      'Practice mindfulness or deep breathing during a break.',
      'Prioritize tasks and tackle the most important ones first.',
      'Socialize with colleagues to build positive relationships.',
      'Avoid heavy, greasy meals that can cause sluggishness.',
      'Organize your workspace for improved focus and efficiency.',
      'Listen to uplifting music to boost your mood.',
      'Try a new healthy midday recipe to keep things interesting.',
      'Include colorful vegetables in your midday meal.',
      'Take a moment to stretch and release tension in your neck and shoulders.',
      'Opt for a midday snack that combines protein and fiber.',
      'Plan your afternoon tasks to manage your time effectively.',
      'Go for a short walk outside to refresh your mind.',
      'Eat mindfully, savoring the flavors of your midday meal.',
      'Try a midday meditation or breathing exercise.',
      'Connect with a friend or family member during your break.',
      'Choose whole grain options for sustained energy.',
      'Stay organized with a to-do list for the afternoon.',
      'Opt for a light and nutritious midday smoothie.',
      'Stand or use a standing desk for part of the midday.',
      'Incorporate leafy greens into your midday meal.',
      'Take a moment to express gratitude for the day so far.',
      'Practice a quick midday yoga routine.',
      'Have a conversation with a colleague to foster connections.',
      'Include a source of healthy fats in your midday snack.',
      'Use aromatherapy with scents like peppermint for alertness.',
      'Take a break from screens and focus on something in the distance.',
      'Include a variety of textures in your midday snack for satisfaction.',
      'Review and adjust your goals for the week during midday.',
      'Enjoy a cup of herbal tea for a calming midday break.',
      'Opt for a plant-based midday meal for a change.',
      'Do a quick midday workout to boost your energy.',
      'Practice gratitude by acknowledging positive aspects of your day.',
      'Snack on a handful of berries for antioxidants.',
      'Take a moment to appreciate the natural light in your environment.',
      'Practice good posture during your midday tasks.',
      'Include a source of vitamin C in your midday meal.',
      'Set aside time for a midday power nap if possible.',
      'Use a midday break for a quick outdoor stroll.',
      'Include a source of lean protein in your midday snack.',
      'Practice a midday desk stretch to alleviate tension.',
      'Enjoy a midday cup of green tea for a gentle energy boost.',
      'Plan a midday break to engage in a creative activity.',
      'Include a variety of colors in your midday meal.',
      'Take a moment to visualize your goals for the afternoon.',
      'Snack on a handful of almonds for a satisfying midday option.',
      'Practice a midday mindfulness walk, focusing on each step.',
      'Set a positive affirmation for the rest of the day.',
      'Include fermented foods in your midday diet for gut health.',
      'Use a midday break to engage in a quick relaxation exercise.',
      'Snack on a piece of dark chocolate for a mood boost.',
      'Take a moment to appreciate the achievements of the morning.',
      'Incorporate a source of iron into your midday meal.',
      'Plan a midday break to listen to an inspiring podcast.',
      'Eat a midday meal with a variety of textures for satisfaction.',
      'Take a moment to breathe deeply and reset your focus.',
      'Include a source of potassium in your midday snack.',
      'Use a midday break to practice gratitude journaling.',
      'Opt for a midday snack with a mix of protein and carbohydrates.',
      'Enjoy a midday cup of chamomile tea for relaxation.',
      'Snack on a handful of walnuts for brain-boosting omega-3s.',
      'Take a moment to appreciate your midday surroundings.',
      'Plan a midday break for a quick desk stretch routine.',
      'Incorporate a source of calcium into your midday meal.',
      'Use a midday break to connect with nature, even if briefly.',
      'Opt for a light and refreshing midday salad.',
      'Snack on a piece of fruit for a natural sugar boost.',
      'Take a moment to stretch your legs during midday.',
      'Practice a midday deep-breathing exercise for relaxation.',
      'Include a source of vitamin D in your midday routine.',
      'Use a midday break to reflect on your accomplishments.',
      'Opt for a midday meal with a variety of flavors.',
      'Snack on a handful of grapes for a sweet midday treat.',
      'Take a moment to express kindness to yourself.',
      'Plan a midday break to enjoy a brief mindfulness meditation.',
      'Incorporate a source of fiber into your midday snack.',
      'Enjoy a midday cup of black or green tea for alertness.',
      'Snack on a piece of cheese for a protein boost.',
      'Take a moment to appreciate the midday sun if possible.',
      'Plan a midday break to enjoy a piece of art or nature.',
      'Incorporate a source of magnesium into your midday routine.',
      'Use a midday break to engage in a positive conversation.',
      'Snack on a handful of cherry tomatoes for a refreshing option.',
      'Take a moment to appreciate the work you\'ve accomplished.',
      'Opt for a midday meal with a mix of textures and temperatures.',
      'Practice a midday mindfulness exercise, focusing on your breath.',
      'Include a source of vitamin E in your midday snack.',
      'Use a midday break to enjoy a brief mindful eating session.',
      'Snack on a handful of pumpkin seeds for a nutrient boost.',
      'Take a moment to express gratitude for your midday break.',
      'Plan a midday break to engage in a hobby or interest.',
      'Incorporate a source of zinc into your midday routine.',
      'Enjoy a midday cup of peppermint tea for a refreshing break.',
      'Snack on a piece of whole-grain toast for a sustained energy boost.',
      'Take a moment to appreciate the beauty of the midday sky.',
      'Opt for a midday meal with a variety of spices for flavor.',
      'Practice a midday desk exercise to enhance circulation.',
      'Include a source of selenium in your midday snack.',
      'Use a midday break to engage in a positive visualization exercise.',
      'Snack on a handful of dried fruit for a sweet midday option.',
      'Take a moment to express kindness to those around you.',
      'Plan a midday break to enjoy a brief mindfulness walk.',
      'Incorporate a source of vitamin A into your midday routine.',
      'Enjoy a midday cup of hibiscus tea for a vibrant break.',
      'Snack on a piece of cucumber for a hydrating midday option.',
      'Take a moment to appreciate the natural sounds of the midday.',
      'Opt for a midday meal with a variety of herbs for freshness.',
      'Practice a midday gratitude exercise, acknowledging positive aspects.',
      'Include a source of potassium in your midday routine.',
      'Use a midday break to engage in a quick positive visualization.',
      'Snack on a handful of mixed nuts for a balanced midday option.',
      'Take a moment to express gratitude for the midday pause.',
      'Plan a midday break to enjoy a brief mindfulness breathing exercise.',
      'Incorporate a source of vitamin K into your midday routine.',
      'Enjoy a midday cup of ginger tea for a warming break.',
      'Snack on a piece of celery for a crunchy midday option.',
      'Take a moment to appreciate the stillness of the midday.',
      'Opt for a midday meal with a variety of textures for enjoyment.',
      'Practice a midday mindfulness check-in, assessing your feelings.',
      'Include a source of copper in your midday routine.',
      'Use a midday break to engage in a positive affirmation practice.',
      'Snack on a handful of blueberries for a antioxidant-rich option.',
      'Take a moment to express kindness to yourself and others.',
      'Plan a midday break to enjoy a brief mindfulness visualization.',
      'Incorporate a source of phosphorus into your midday routine.',
      'Enjoy a midday cup of rooibos tea for a caffeine-free break.',
      'Snack on a piece of pineapple for a tropical midday option.',
      'Take a moment to appreciate the balance of the midday.',
      'Opt for a midday meal with a variety of textures and colors for vibrancy.',
      'Practice a midday desk stretch to alleviate tension and improve posture.',
      'Include a source of manganese in your midday routine.',
      'Use a midday break to engage in a positive self-talk exercise.',
      'Snack on a handful of strawberries for a refreshing midday option.',
      'Take a moment to express gratitude for the midday tranquility.',
      'Plan a midday break to enjoy a brief mindfulness gratitude exercise.',
      'Incorporate a source of potassium into your midday routine.',
      'Enjoy a midday cup of chamomile tea for a calming break.',
      'Snack on a piece of watermelon for a hydrating midday option.',
      'Take a moment to appreciate the warmth of the midday.',
      'Opt for a midday meal with a mix of textures and temperatures for enjoyment.',
      'Practice a midday mindfulness exercise, focusing on your breath and surroundings.',
      'Include a source of vitamin E in your midday routine.',
      'Use a midday break to engage in a positive visualization and affirmations.',
      'Snack on a handful of almonds for a satisfying and nutritious midday option.',
    ],
    'afternoon': [
      'Have a nutritious snack to maintain energy levels.',
      'Take a brisk walk or stretch to combat midday fatigue.',
      'Stay hydrated with water or herbal tea.',
      'Prioritize tasks and break them into manageable steps.',
      'Avoid excessive caffeine intake to prevent energy crashes.',
      'Practice mindfulness or meditation for mental clarity.',
      'Engage in a creative activity to refresh your mind.',
      'Connect with a friend or family member for support.',
      'Review and adjust your goals for the day if needed.',
      'Consider a power nap if you\'re feeling fatigued.',
      'Snack on a handful of nuts for a quick and nutritious pick-me-up.',
      'Take a moment to breathe deeply and refocus your mind.',
      'Enjoy a balanced and light lunch for sustained energy.',
      'Stretch your body to release tension and improve flexibility.',
      'Stay organized by tidying up your workspace.',
      'Include protein in your afternoon snack for satiety.',
      'Practice mindfulness during your afternoon tasks.',
      'Take a break to step outside and get some fresh air.',
      'Plan an afternoon walk to boost your mood and activity levels.',
      'Eat a colorful and diverse salad for a nutrient-rich lunch.',
      'Stay connected with colleagues for a positive work environment.',
      'Snack on a piece of fruit for natural sweetness.',
      'Do a quick office-friendly workout to energize yourself.',
      'Stay hydrated with infused water for added flavor.',
      'Set boundaries for your work to avoid burnout.',
      'Snack on a handful of dried fruits for a sweet treat.',
      'Incorporate whole grains into your afternoon meal for lasting energy.',
      'Take a moment to express gratitude for the day\'s accomplishments.',
      'Practice deep breathing to manage stress in the afternoon.',
      'Opt for a protein-rich afternoon snack for sustained energy.',
      'Review your to-do list and prioritize tasks for the rest of the day.',
      'Snack on a handful of cherry tomatoes for a refreshing option.',
      'Incorporate lean protein into your afternoon meal.',
      'Take short breaks to stretch and move around.',
      'Snack on a yogurt parfait with granola for a satisfying option.',
      'Set a positive intention for the second half of your day.',
      'Stay mindful of your posture during afternoon tasks.',
      'Snack on a handful of trail mix for a balanced option.',
      'Practice gratitude for the opportunities in your afternoon.',
      'Incorporate leafy greens into your afternoon meal.',
      'Take a moment to stretch your neck and shoulders.',
      'Snack on a piece of dark chocolate for a mood boost.',
      'Organize your to-do list into categories for better focus.',
      'Incorporate a source of healthy fats into your afternoon snack.',
      'Take a break to enjoy a cup of herbal tea.',
      'Snack on a handful of edamame for a protein-packed option.',
      'Review and celebrate your achievements from the morning.',
      'Incorporate a variety of colors into your afternoon snack.',
      'Practice mindfulness while enjoying your afternoon snack.',
      'Snack on a handful of almonds for a satisfying and nutritious option.',
      'Take a break to move and stretch your legs.',
      'Enjoy a balanced and flavorful afternoon meal.',
      'Snack on a piece of whole-grain toast with nut butter for energy.',
      'Stay focused by minimizing multitasking.',
      'Incorporate a source of vitamin C into your afternoon routine.',
      'Take a moment to appreciate the natural light in your workspace.',
      'Snack on a handful of grapes for a sweet and hydrating option.',
      'Practice gratitude for the positive aspects of your afternoon.',
      'Incorporate a source of protein into your afternoon meal.',
      'Take a break to enjoy a healthy smoothie.',
      'Snack on a handful of walnuts for brain-boosting omega-3s.',
      'Review your goals and adjust them if necessary.',
      'Incorporate a source of iron into your afternoon routine.',
      'Take a moment to express kindness to yourself and others.',
      'Snack on a piece of cheese for a protein boost.',
      'Set aside time for a short afternoon meditation.',
      'Incorporate a source of magnesium into your afternoon routine.',
      'Take a break to enjoy a cup of green tea for alertness.',
      'Snack on a handful of mixed berries for antioxidants.',
      'Practice deep breathing to relax and reset your mind.',
      'Incorporate a source of potassium into your afternoon routine.',
      'Take a break to appreciate the beauty of the afternoon sky.',
      'Snack on a handful of pumpkin seeds for a nutrient boost.',
      'Set a positive affirmation for the remainder of the day.',
      'Incorporate a source of fiber into your afternoon snack.',
      'Take a moment to express gratitude for your afternoon break.',
      'Snack on a piece of fruit for a natural energy boost.',
      'Practice mindfulness during your afternoon break.',
      'Incorporate a source of vitamin D into your afternoon routine.',
      'Take a short walk to recharge your mind.',
      'Snack on a handful of almonds for a satisfying and nutritious option.',
      'Incorporate a source of zinc into your afternoon routine.',
      'Take a break to enjoy a cup of chamomile tea for relaxation.',
      'Snack on a piece of cucumber for a hydrating option.',
      'Set aside time for a short afternoon workout.',
      'Incorporate a source of vitamin A into your afternoon routine.',
      'Take a moment to express gratitude for the opportunities in your afternoon.',
      'Snack on a handful of cherry tomatoes for a refreshing option.',
      'Practice gratitude for the positive aspects of your afternoon.',
      'Incorporate a source of potassium into your afternoon routine.',
      'Take a break to move and stretch your legs.',
      'Snack on a piece of dark chocolate for a mood boost.',
      'Set a positive intention for the second half of your day.',
      'Stay mindful of your posture during afternoon tasks.',
      'Snack on a handful of trail mix for a balanced option.',
      'Practice gratitude for the opportunities in your afternoon.',
      'Incorporate leafy greens into your afternoon meal.',
      'Take a moment to stretch your neck and shoulders.',
      'Snack on a piece of dark chocolate for a mood boost.',
      'Organize your to-do list into categories for better focus.',
      'Incorporate a source of healthy fats into your afternoon snack.',
      'Take a break to enjoy a cup of herbal tea.',
      'Snack on a handful of edamame for a protein-packed option.',
      'Review and celebrate your achievements from the morning.',
      'Incorporate a variety of colors into your afternoon snack.',
      'Practice mindfulness while enjoying your afternoon snack.',
      'Snack on a handful of almonds for a satisfying and nutritious option.',
      'Take a break to move and stretch your legs.',
      'Enjoy a balanced and flavorful afternoon meal.',
      'Snack on a piece of whole-grain toast with nut butter for energy.',
      'Stay focused by minimizing multitasking.',
      'Incorporate a source of vitamin C into your afternoon routine.',
      'Take a moment to appreciate the natural light in your workspace.',
      'Snack on a handful of grapes for a sweet and hydrating option.',
      'Practice gratitude for the positive aspects of your afternoon.',
      'Incorporate a source of protein into your afternoon meal.',
      'Take a break to enjoy a healthy smoothie.',
      'Snack on a handful of walnuts for brain-boosting omega-3s.',
      'Review your goals and adjust them if necessary.',
      'Incorporate a source of iron into your afternoon routine.',
      'Take a moment to express kindness to yourself and others.',
      'Snack on a piece of cheese for a protein boost.',
      'Set aside time for a short afternoon meditation.',
      'Incorporate a source of magnesium into your afternoon routine.',
      'Take a break to enjoy a cup of green tea for alertness.',
      'Snack on a handful of mixed berries for antioxidants.',
      'Practice deep breathing to relax and reset your mind.',
      'Incorporate a source of potassium into your afternoon routine.',
      'Take a break to appreciate the beauty of the afternoon sky.',
      'Snack on a handful of pumpkin seeds for a nutrient boost.',
      'Set a positive affirmation for the remainder of the day.',
      'Incorporate a source of fiber into your afternoon snack.',
      'Take a moment to express gratitude for your afternoon break.',
      'Snack on a piece of fruit for a natural energy boost.',
      'Practice mindfulness during your afternoon break.',
      'Incorporate a source of vitamin D into your afternoon routine.',
      'Take a short walk to recharge your mind.',
      'Snack on a handful of almonds for a satisfying and nutritious option.',
      'Incorporate a source of zinc into your afternoon routine.',
      'Take a break to enjoy a cup of chamomile tea for relaxation.',
      'Snack on a piece of cucumber for a hydrating option.',
      'Set aside time for a short afternoon workout.',
      'Incorporate a source of vitamin A into your afternoon routine.',
      'Take a moment to express gratitude for the opportunities in your afternoon.',
      'Snack on a handful of cherry tomatoes for a refreshing option.',
      'Practice gratitude for the positive aspects of your afternoon.',
      'Incorporate a source of potassium into your afternoon routine.',
      'Take a break to move and stretch your legs.',
      'Snack on a piece of dark chocolate for a mood boost.',
      'Set a positive intention for the second half of your day.',
      'Stay mindful of your posture during afternoon tasks.',
      'Snack on a handful of trail mix for a balanced option.',
      'Practice gratitude for the opportunities in your afternoon.',
      'Incorporate leafy greens into your afternoon meal.',
      'Take a moment to stretch your neck and shoulders.',
      'Snack on a piece of dark chocolate for a mood boost.',
      'Organize your to-do list into categories for better focus.',
      'Incorporate a source of healthy fats into your afternoon snack.',
      'Take a break to enjoy a cup of herbal tea.',
      'Snack on a handful of edamame for a protein-packed option.',
      'Review and celebrate your achievements from the morning.',
      'Incorporate a variety of colors into your afternoon snack.',
      'Practice mindfulness while enjoying your afternoon snack.',
      'Snack on a handful of almonds for a satisfying and nutritious option.',
      'Take a break to move and stretch your legs.',
      'Enjoy a balanced and flavorful afternoon meal.',
      'Snack on a piece of whole-grain toast with nut butter for energy.',
      'Stay focused by minimizing multitasking.',
      'Incorporate a source of vitamin C into your afternoon routine.',
      'Take a moment to appreciate the natural light in your workspace.',
      'Snack on a handful of grapes for a sweet and hydrating option.',
      'Practice gratitude for the positive aspects of your afternoon.',
      'Incorporate a source of protein into your afternoon meal.',
      'Take a break to enjoy a healthy smoothie.',
      'Snack on a handful of walnuts for brain-boosting omega-3s.',
      'Review your goals and adjust them if necessary.',
      'Incorporate a source of iron into your afternoon routine.',
      'Take a moment to express kindness to yourself and others.',
      'Snack on a piece of cheese for a protein boost.',
      'Set aside time for a short afternoon meditation.',
      'Incorporate a source of magnesium into your afternoon routine.',
      'Take a break to enjoy a cup of green tea for alertness.',
      'Snack on a handful of mixed berries for antioxidants.',
      'Practice deep breathing to relax and reset your mind.',
      'Incorporate a source of potassium into your afternoon routine.',
      'Take a break to appreciate the beauty of the afternoon sky.',
      'Snack on a handful of pumpkin seeds for a nutrient boost.',
      'Set a positive affirmation for the remainder of the day.',
      'Incorporate a source of fiber into your afternoon snack.',
      'Take a moment to express gratitude for your afternoon break.',
      'Snack on a piece of fruit for a natural energy boost.',
      'Practice mindfulness during your afternoon break.',
      'Incorporate a source of vitamin D into your afternoon routine.',
      'Take a short walk to recharge your mind.',
      'Snack on a handful of almonds for a satisfying and nutritious option.',
      'Incorporate a source of zinc into your afternoon routine.',
      'Take a break to enjoy a cup of chamomile tea for relaxation.',
      'Snack on a piece of cucumber for a hydrating option.',
      'Set aside time for a short afternoon workout.',
      'Incorporate a source of vitamin A into your afternoon routine.',
      'Take a moment to express gratitude for the opportunities in your afternoon.',
      'Snack on a handful of cherry tomatoes for a refreshing option.',
      'Practice gratitude for the positive aspects of your afternoon.',
      'Incorporate a source of potassium into your afternoon routine.',
      'Take a break to move and stretch your legs.',
      'Snack on a piece of dark chocolate for a mood boost.',
      'Set a positive intention for the second half of your day.',
      'Stay mindful of your posture during afternoon tasks.',
      'Snack on a handful of trail mix for a balanced option.',
      'Practice gratitude for the opportunities in your afternoon.',
    ],
    'evening': [
      'Reflect on your achievements and areas for improvement today.',
      'Unplug from electronic devices at least one hour before bedtime.',
      'Practice gentle stretching to relax your muscles.',
      'Set a consistent bedtime for better sleep quality.',
      'Write down your thoughts and worries in a journal to clear your mind.',
      'Avoid heavy meals close to bedtime for better digestion.',
      'Read a book or listen to calming music before bedtime.',
      'Create a calming bedtime routine to signal your body it\'s time to sleep.',
      'Limit caffeine intake in the evening to promote restful sleep.',
      'Practice mindfulness or meditation to relax your mind.',
      'Plan your tasks for the next day to reduce nighttime stress.',
      'Enjoy a warm cup of caffeine-free tea for relaxation.',
      'Dim the lights in the evening to signal your body it\'s time to wind down.',
      'Engage in a soothing bath or shower before bedtime.',
      'Set a technology curfew to improve your sleep quality.',
      'Avoid intense workouts close to bedtime for better sleep.',
      'Create a comfortable and calming sleep environment.',
      'Reflect on three positive moments from your day.',
      'Practice gratitude for the experiences of the evening.',
      'Limit screen time in the evening for better sleep hygiene.',
      'Try a gentle yoga routine to relax your body and mind.',
      'Enjoy a light evening snack if you\'re hungry.',
      'Avoid stimulating activities close to bedtime.',
      'Listen to a calming podcast or audiobook before sleep.',
      'Set boundaries for work-related activities in the evening.',
      'Practice deep breathing exercises to promote relaxation.',
      'Create a relaxing playlist for your evening routine.',
      'Wind down with a creative or artistic activity.',
      'Express kindness and gratitude towards others in the evening.',
      'Review your achievements and celebrate small victories.',
      'Disconnect from work emails and messages in the evening.',
      'Spend quality time with loved ones in the evening.',
      'Enjoy a calming herbal infusion for better sleep.',
      'Practice a short mindfulness meditation before bedtime.',
      'Reflect on your goals and aspirations in the evening.',
      'Limit exposure to bright screens for at least an hour before bed.',
      'Engage in a light evening stroll for relaxation.',
      'Set aside time for a relaxation or breathing exercise.',
      'Avoid heavy or rich desserts close to bedtime.',
      'Create a serene and clutter-free bedroom environment.',
      'Practice progressive muscle relaxation for better sleep.',
      'Limit the consumption of sugary snacks in the evening.',
      'Reflect on moments of joy and gratitude from your evening.',
      'Use blackout curtains to create a dark sleeping environment.',
      'Enjoy a cup of warm milk or a dairy-free alternative.',
      'Practice a gentle evening meditation for calmness.',
      'Limit exposure to news or stressful content in the evening.',
      'Use aromatherapy with calming scents in your evening routine.',
      'Reflect on your learnings and experiences from the evening.',
      'Create a technology-free zone in your bedroom for better sleep.',
      'Engage in a calming hobby, such as drawing or knitting.',
      'Practice a short and calming bedtime yoga routine.',
      'Limit the intake of caffeinated beverages in the evening.',
      'Create a gratitude journal for your evening reflections.',
      'Listen to nature sounds or white noise for a peaceful sleep environment.',
      'Savor a piece of dark chocolate as a small evening treat.',
      'Set a consistent bedtime routine to signal your body for sleep.',
      'Reflect on the positive connections and interactions of your evening.',
      'Use lavender-scented products for a soothing bedtime atmosphere.',
      'Practice a gentle body scan meditation for relaxation.',
      'Avoid discussing stressful topics close to bedtime.',
      'Create a comfortable sleep routine to signal your body for rest.',
      'Reflect on the beauty of the evening sky.',
      'Limit exposure to blue light from screens before bedtime.',
      'Engage in a light evening yoga session for relaxation.',
      'Practice mindfulness while enjoying a warm evening beverage.',
      'Set aside time for gratitude journaling in the evening.',
      'Limit evening caffeine to promote a restful night\'s sleep.',
      'Create a calming bedtime ritual with soothing music.',
      'Reflect on moments of laughter and joy from your evening.',
      'Use gentle and dim lighting in the evening for a calming atmosphere.',
      'Enjoy a piece of fruit as a light and healthy evening snack.',
      'Practice visualization of a peaceful and calming scene before sleep.',
      'Avoid strenuous physical activities close to bedtime.',
      'Set a consistent sleep schedule to regulate your body\'s internal clock.',
      'Reflect on the positive aspects of your day during the evening.',
      'Engage in a brief gratitude meditation before bedtime.',
      'Practice gentle neck and shoulder stretches for relaxation.',
      'Limit exposure to stimulating content on social media in the evening.',
      'Create a bedtime routine that includes calming activities.',
      'Reflect on your favorite moments and experiences of the evening.',
      'Use soft and comfortable bedding for a restful night\'s sleep.',
      'Practice a short and calming breathing exercise before bedtime.',
      'Avoid heavy or spicy foods close to bedtime for better sleep.',
      'Create a peaceful evening routine with soothing scents and sounds.',
      'Reflect on your personal growth and achievements from the evening.',
      'Limit the use of electronic devices with bright screens in the evening.',
      'Engage in a gentle evening meditation for relaxation.',
      'Practice a progressive muscle relaxation exercise to release tension.',
      'Avoid excessive consumption of alcohol in the evening for better sleep.',
      'Set a consistent wind-down time to prepare your body for sleep.',
      'Reflect on the positive impact you made during the evening.',
      'Use soft and calming colors in your bedroom for a serene atmosphere.',
      'Practice gratitude for the experiences and lessons of the evening.',
      'Limit exposure to loud or disruptive noises in the evening.',
      'Create a relaxing playlist with your favorite calming tunes.',
      'Reflect on the small victories and achievements of your evening.',
      'Enjoy a cup of herbal tea with calming ingredients before bedtime.',
      'Practice gentle and restorative yoga poses for relaxation.',
      'Avoid intense or stimulating activities close to bedtime.',
      'Set a positive affirmation for a peaceful night\'s sleep.',
      'Reflect on moments of love and connection from your evening.',
      'Use blackout curtains to create a dark and restful sleep environment.',
      'Practice a short body scan meditation to release tension.',
      'Limit the use of electronic devices in the hour leading up to bedtime.',
      'Engage in a brief mindfulness exercise for relaxation.',
      'Create a cozy and inviting sleep space for a restful night.',
      'Reflect on the beauty of nature and the environment in the evening.',
      'Set a consistent bedtime routine to signal your body for restful sleep.',
      'Practice a gentle and calming bedtime routine to unwind.',
      'Limit the consumption of heavy or greasy foods close to bedtime.',
      'Enjoy a light and healthy evening snack if hungry.',
      'Use a sleep mask to block out any remaining light for better sleep.',
      'Reflect on moments of peace and tranquility from your evening.',
      'Practice a short gratitude meditation before bedtime.',
      'Avoid engaging in stimulating conversations close to bedtime.',
      'Create a bedtime routine that prioritizes relaxation and self-care.',
      'Reflect on the positive energy and experiences of your evening.',
      'Limit exposure to stressful or challenging content in the evening.',
      'Engage in a calming activity, such as gentle stretching, before bedtime.',
      'Set a consistent sleep environment to promote restful sleep.',
      'Practice a short and calming mindfulness meditation before bedtime.',
      'Limit the intake of sugary snacks and desserts in the evening.',
      'Create a calming bedtime environment with soft lighting and scents.',
      'Reflect on moments of joy and contentment from your evening.',
      'Use a white noise machine or app for a peaceful sleep atmosphere.',
      'Practice a gentle evening yoga sequence for relaxation.',
      'Avoid excessive consumption of caffeinated beverages in the evening.',
      'Set a consistent sleep routine to regulate your body\'s circadian rhythm.',
      'Reflect on moments of gratitude and appreciation from your evening.',
      'Engage in a calming bedtime routine to signal your body for sleep.',
      'Limit exposure to blue light from electronic devices before bedtime.',
      'Practice deep breathing exercises to relax your mind and body.',
      'Create a calming bedtime ritual with your favorite activities.',
      'Reflect on moments of calm and serenity from your evening.',
      'Use soft and comfortable sleepwear for a cozy night\'s sleep.',
      'Practice a short and gentle stretching routine before bedtime.',
      'Limit the use of electronic devices in the bedroom for better sleep hygiene.',
      'Enjoy a cup of herbal tea with calming herbs for relaxation.',
      'Set a consistent wind-down time to prepare for a restful night\'s sleep.',
      'Reflect on moments of laughter and happiness from your evening.',
      'Engage in a calming activity, such as reading, before bedtime.',
      'Avoid consuming excessive amounts of caffeine in the evening.',
      'Create a bedtime routine that includes activities you enjoy.',
      'Reflect on moments of peace and tranquility from your evening.',
      'Use blackout curtains to create a dark sleep environment.',
      'Practice a gentle and restful bedtime yoga routine for relaxation.',
      'Limit exposure to bright screens in the evening for better sleep.',
      'Set a consistent sleep schedule to regulate your body\'s internal clock.',
      'Reflect on moments of connection and togetherness from your evening.',
      'Engage in a calming visualization exercise before bedtime.',
      'Avoid engaging in stimulating or intense conversations close to bedtime.',
      'Create a calming bedtime routine that includes self-care activities.',
      'Reflect on moments of gratitude and appreciation from your evening.',
      'Practice a short and calming mindfulness meditation before sleep.',
      'Limit exposure to loud or disruptive noises in the evening.',
      'Use soft and calming scents in your bedroom for a peaceful sleep environment.',
      'Set a consistent sleep routine to signal your body for restful sleep.',
      'Reflect on moments of joy and contentment from your evening.',
      'Engage in a calming activity, such as gentle stretching, before bedtime.',
      'Limit exposure to blue light from electronic devices before bedtime.',
      'Practice deep breathing exercises to relax your mind and body.',
      'Create a calming bedtime ritual with your favorite activities.',
      'Reflect on moments of calm and serenity from your evening.',
      'Use soft and comfortable sleepwear for a cozy night\'s sleep.',
      'Practice a short and gentle stretching routine before bedtime.',
      'Limit the use of electronic devices in the bedroom for better sleep hygiene.',
      'Enjoy a cup of herbal tea with calming herbs for relaxation.',
      'Set a consistent wind-down time to prepare for a restful night\'s sleep.',
      'Reflect on moments of laughter and happiness from your evening.',
      'Engage in a calming activity, such as reading, before bedtime.',
      'Avoid consuming excessive amounts of caffeine in the evening.',
      'Create a bedtime routine that includes activities you enjoy.',
      'Reflect on moments of peace and tranquility from your evening.',
      'Use blackout curtains to create a dark sleep environment.',
      'Practice a gentle and restful bedtime yoga routine for relaxation.',
      'Limit exposure to bright screens in the evening for better sleep.',
      'Set a consistent sleep schedule to regulate your body\'s internal clock.',
      'Reflect on moments of connection and togetherness from your evening.',
      'Engage in a calming visualization exercise before bedtime.',
      'Avoid engaging in stimulating or intense conversations close to bedtime.',
      'Create a calming bedtime routine that includes self-care activities.',
      'Reflect on moments of gratitude and appreciation from your evening.',
      'Practice a short and calming mindfulness meditation before sleep.',
      'Limit exposure to loud or disruptive noises in the evening.',
      'Use soft and calming scents in your bedroom for a peaceful sleep environment.',
      'Set a consistent sleep routine to signal your body for restful sleep.',
      'Reflect on moments of joy and contentment from your evening.',
    ],
    'night': [
      'Create a calming bedtime routine to signal your body for sleep.',
      'Dim the lights in your living space to promote relaxation.',
      'Limit exposure to bright screens in the hour leading up to bedtime.',
      'Practice gentle stretching or yoga before getting into bed.',
      'Set a consistent bedtime to regulate your sleep-wake cycle.',
      'Avoid heavy or spicy foods close to bedtime for better digestion.',
      'Use blackout curtains to create a dark and restful sleep environment.',
      'Read a calming book or listen to a soothing podcast before bedtime.',
      'Practice deep breathing exercises to relax your mind and body.',
      'Reflect on three positive moments from your day before sleep.',
      'Avoid consuming caffeine in the evening to improve sleep quality.',
      'Keep your bedroom cool and comfortable for a restful night\'s sleep.',
      'Use a comfortable pillow and mattress for better sleep support.',
      'Create a sleep-friendly environment with minimal noise.',
      'Limit the use of electronic devices in the bedroom for better sleep hygiene.',
      'Enjoy a warm cup of caffeine-free tea as part of your bedtime routine.',
      'Practice mindfulness meditation to calm your thoughts before sleep.',
      'Engage in a brief gratitude practice to foster positive emotions.',
      'Avoid stimulating activities, such as intense workouts, close to bedtime.',
      'Set a positive intention for the night and the upcoming day.',
      'Create a worry list to clear your mind before bedtime.',
      'Limit the intake of sugary snacks and desserts in the evening.',
      'Use aromatherapy with calming scents, such as lavender, in your bedroom.',
      'Practice progressive muscle relaxation to release tension.',
      'Reflect on moments of joy and gratitude from your evening.',
      'Avoid discussing stressful topics or engaging in arguments before bedtime.',
      'Try a guided sleep meditation to ease into a peaceful night\'s sleep.',
      'Create a comfortable and calming bedtime routine for consistent sleep.',
      'Use a sleep mask to block out any remaining light for better sleep.',
      'Listen to calming music or nature sounds to promote relaxation.',
      'Set a consistent wake-up time to regulate your sleep pattern.',
      'Practice visualization of a peaceful and serene place before sleep.',
      'Avoid checking emails or engaging in work-related activities close to bedtime.',
      'Limit exposure to news or stressful content in the evening.',
      'Create a technology-free wind-down period before bedtime.',
      'Reflect on moments of calmness and serenity from your day.',
      'Avoid excessive alcohol consumption in the evening for better sleep quality.',
      'Engage in a light stretching routine to release tension.',
      'Practice a body scan meditation to relax each part of your body.',
      'Limit the use of alarms with loud or jarring sounds to wake up gently.',
      'Create a consistent pre-sleep routine to signal your body for rest.',
      'Avoid consuming large meals close to bedtime for better digestion.',
      'Use white noise or a fan to create a soothing sleep environment.',
      'Reflect on the positive aspects of your day before sleep.',
      'Avoid using electronic devices as a distraction if you can\'t sleep.',
      'Set a consistent wind-down time to prepare for bedtime.',
      'Practice a short mindfulness exercise for relaxation.',
      'Avoid dwelling on negative thoughts or worries before sleep.',
      'Use soft and comfortable bedding for a cozy night\'s sleep.',
      'Engage in a calming activity, such as reading, to wind down.',
      'Reflect on moments of gratitude and appreciation from your night.',
      'Limit exposure to bright screens in the hour leading up to sleep.',
      'Create a bedtime routine that includes self-care activities.',
      'Practice gentle and restorative yoga poses for relaxation.',
      'Avoid engaging in stimulating or intense conversations close to bedtime.',
      'Set a consistent sleep schedule to regulate your body\'s internal clock.',
      'Reflect on moments of connection and togetherness from your night.',
      'Engage in a calming visualization exercise before sleep.',
      'Avoid consuming excessive amounts of caffeine in the evening.',
      'Create a calming bedtime routine that includes activities you enjoy.',
      'Reflect on moments of peace and tranquility from your night.',
      'Use blackout curtains to create a dark sleep environment.',
      'Practice a gentle and restful bedtime yoga routine for relaxation.',
      'Limit exposure to bright screens in the evening for better sleep.',
      'Set a consistent sleep schedule to regulate your body\'s internal clock.',
      'Reflect on moments of connection and togetherness from your night.',
      'Engage in a calming visualization exercise before sleep.',
      'Avoid engaging in stimulating or intense conversations close to bedtime.',
      'Create a calming bedtime routine that includes self-care activities.',
      'Reflect on moments of gratitude and appreciation from your night.',
      'Practice a short and calming mindfulness meditation before sleep.',
      'Limit exposure to loud or disruptive noises in the evening.',
      'Use soft and calming scents in your bedroom for a peaceful sleep environment.',
      'Set a consistent sleep routine to signal your body for restful sleep.',
      'Reflect on moments of joy and contentment from your night.',
      'Engage in a calming activity, such as gentle stretching, before bedtime.',
      'Limit exposure to blue light from electronic devices before bedtime.',
      'Practice deep breathing exercises to relax your mind and body.',
      'Create a calming bedtime ritual with your favorite activities.',
      'Reflect on moments of calm and serenity from your night.',
      'Use soft and comfortable sleepwear for a cozy night\'s sleep.',
      'Practice a short and gentle stretching routine before bedtime.',
      'Limit the use of electronic devices in the bedroom for better sleep hygiene.',
      'Enjoy a cup of herbal tea with calming herbs for relaxation.',
      'Set a consistent wind-down time to prepare for a restful night\'s sleep.',
      'Reflect on moments of laughter and happiness from your night.',
      'Engage in a calming activity, such as reading, before bedtime.',
      'Avoid consuming excessive amounts of caffeine in the evening.',
      'Create a bedtime routine that includes activities you enjoy.',
      'Reflect on moments of peace and tranquility from your night.',
      'Use blackout curtains to create a dark sleep environment.',
      'Practice a gentle and restful bedtime yoga routine for relaxation.',
      'Limit exposure to bright screens in the evening for better sleep.',
      'Set a consistent sleep schedule to regulate your body\'s internal clock.',
      'Reflect on moments of connection and togetherness from your night.',
      'Engage in a calming visualization exercise before sleep.',
      'Avoid engaging in stimulating or intense conversations close to bedtime.',
      'Create a calming bedtime routine that includes self-care activities.',
      'Reflect on moments of gratitude and appreciation from your night.',
      'Practice a short and calming mindfulness meditation before sleep.',
      'Limit exposure to loud or disruptive noises in the evening.',
      'Use soft and calming scents in your bedroom for a peaceful sleep environment.',
      'Set a consistent sleep routine to signal your body for restful sleep.',
      'Reflect on moments of joy and contentment from your night.',
      'Engage in a calming activity, such as gentle stretching, before bedtime.',
      'Limit exposure to blue light from electronic devices before bedtime.',
      'Practice deep breathing exercises to relax your mind and body.',
      'Create a calming bedtime ritual with your favorite activities.',
      'Reflect on moments of calm and serenity from your night.',
      'Use soft and comfortable sleepwear for a cozy night\'s sleep.',
      'Practice a short and gentle stretching routine before bedtime.',
      'Limit the use of electronic devices in the bedroom for better sleep hygiene.',
      'Enjoy a cup of herbal tea with calming herbs for relaxation.',
      'Set a consistent wind-down time to prepare for a restful night\'s sleep.',
      'Reflect on moments of laughter and happiness from your night.',
      'Engage in a calming activity, such as reading, before bedtime.',
      'Avoid consuming excessive amounts of caffeine in the evening.',
      'Create a bedtime routine that includes activities you enjoy.',
      'Reflect on moments of peace and tranquility from your night.',
      'Use blackout curtains to create a dark sleep environment.',
      'Practice a gentle and restful bedtime yoga routine for relaxation.',
      'Limit exposure to bright screens in the evening for better sleep.',
      'Set a consistent sleep schedule to regulate your body\'s internal clock.',
      'Reflect on moments of connection and togetherness from your night.',
      'Engage in a calming visualization exercise before sleep.',
      'Avoid engaging in stimulating or intense conversations close to bedtime.',
      'Create a calming bedtime routine that includes self-care activities.',
      'Reflect on moments of gratitude and appreciation from your night.',
      'Practice a short and calming mindfulness meditation before sleep.',
      'Limit exposure to loud or disruptive noises in the evening.',
      'Use soft and calming scents in your bedroom for a peaceful sleep environment.',
      'Set a consistent sleep routine to signal your body for restful sleep.',
      'Reflect on moments of joy and contentment from your night.',
      'Engage in a brief mindfulness meditation to relax your mind.',
      'Create a calming playlist with soothing music for bedtime.',
      'Reflect on moments of gratitude and appreciation from the day.',
      'Avoid heavy or intense discussions close to bedtime.',
      'Use a comfortable sleep mask to block out any remaining light.',
      'Practice a gentle and calming visualization exercise for sleep.',
      'Limit exposure to bright screens in the hour leading up to bedtime.',
      'Reflect on positive affirmations before drifting off to sleep.',
      'Enjoy a cup of chamomile tea for its calming properties.',
      'Practice a calming body scan meditation for relaxation.',
      'Set a consistent wind-down time to signal your body for sleep.',
      'Avoid discussing work-related matters close to bedtime.',
      'Use a weighted blanket for a comforting and secure feeling.',
      'Create a serene and clutter-free sleep environment.',
      'Reflect on moments of joy and contentment from your night.',
      'Practice deep breathing exercises to calm your nervous system.',
      'Limit exposure to news or stressful content before sleep.',
      'Engage in light stretching or gentle yoga for relaxation.',
      'Use a lavender-scented diffuser for a soothing sleep atmosphere.',
      'Reflect on moments of love and connection from your night.',
      'Avoid consuming caffeine in the evening to promote better sleep.',
      'Practice a short and gentle bedtime yoga sequence.',
      'Set a consistent sleep routine for a more restful night.',
      'Enjoy a warm cup of milk or a dairy-free alternative.',
      'Reflect on moments of laughter and happiness from the day.',
      'Practice progressive muscle relaxation to release tension.',
      'Limit the use of electronic devices in the bedroom for better sleep.',
      'Use a calming app with guided sleep meditations.',
      'Create a gratitude jar to write down positive moments each night.',
      'Reflect on moments of personal growth and self-improvement.',
      'Practice a short mindfulness exercise to calm your mind.',
      'Set a consistent bedtime to regulate your sleep-wake cycle.',
      'Avoid engaging in stimulating activities close to bedtime.',
      'Use a sleep-inducing essential oil, such as lavender, on your pillow.',
      'Reflect on moments of kindness and compassion from your night.',
      'Practice a gentle and restorative bedtime yoga routine.',
      'Limit exposure to blue light from electronic devices in the evening.',
      'Engage in a brief meditation on gratitude and positivity.',
      'Use blackout curtains to create a dark and restful sleep environment.',
      'Reflect on moments of peace and tranquility from your night.',
      'Practice a short and calming mindfulness meditation before sleep.',
      'Limit exposure to loud or disruptive noises in the evening.',
      'Create a calming bedtime ritual with your favorite activities.',
      'Reflect on moments of joy and contentment from your night.',
      'Use soft and comfortable sleepwear for a cozy night\'s sleep.',
      'Practice a short and gentle stretching routine before bedtime.',
      'Limit the use of electronic devices in the bedroom for better sleep hygiene.',
      'Enjoy a cup of herbal tea with calming herbs for relaxation.',
      'Set a consistent wind-down time to prepare for a restful night\'s sleep.',
      'Reflect on moments of laughter and happiness from your night.',
      'Engage in a calming activity, such as reading, before bedtime.',
      'Avoid consuming excessive amounts of caffeine in the evening.',
      'Create a bedtime routine that includes activities you enjoy.',
      'Reflect on moments of peace and tranquility from your night.',
    ],
  };

  // Shuffle the list for the corresponding time of day
  healthTips[timeOfDay]?.shuffle();

  return healthTips[timeOfDay]?.first ?? 'No tips available';
}
